---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-golem-tenant
spec:
  interval: 30m
  chart:
    spec:
      chart: tenant
      version: 7.0.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    tenant:
      name: golem-tenant
      pools:
        - servers: 4
          name: pool-0
          volumesPerServer: 1
          size: 32Gi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsNonRoot: true
          containerSecurityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      certificate:
        requestAutoCert: false
        externalCertSecret:
          - name: golem-tenant-tls
            type: cert-manager.io/v1
