---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: golem-tenant-certmanager-cert
  namespace: minio-golem-tenant
spec:
  dnsNames:
    - "minio.minio-golem-tenant"
    - "minio.minio-golem-tenant.svc"
    - "minio.minio-golem-tenant.svc.cluster.local"
    - "*.golem-tenant-hl.minio-golem-tenant.svc.cluster.local"
    - "*.minio-golem-tenant.svc.cluster.local"
    - "*.golem-tenant.minio.minio-golem-tenant.svc.cluster.local"
  secretName: golem-tenant-tls
  issuerRef:
    name: golem-tenant-ca-issuer
