---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./golem-tenant-ca-certificate.yaml
  - ./golem-tenant-ca-issuer.yaml
  - ./golem-tenant-certificate.yaml
