---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./operator-ca-tls-secret.yaml
  - ./operator-ca-issuer.yaml
  - ./sts-tls-certificate.yaml
